name: safe_guard
description: "SafeGuard Nigeria - Emergency Contact Directory"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http: ^1.1.0

  # URL launching (phone calls, links)
  url_launcher: ^6.3.0

  # PDF generation & printing
  pdf: ^3.10.8
  printing: ^5.11.1

  # Icons
  cupertino_icons: ^1.0.8

  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800